name: task-vectors
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - brotlipy
  - bzip2
  - ca-certificates
  - cffi
  - cryptography
  - cudatoolkit
  - ffmpeg
  - freetype
  - giflib
  - m2-gmp
  - m2-libgnutls
  - intel-openmp
  - jbig
  - jpeg
  - lame
  - lcms2
  - lerc
  - libdeflate
  - libffi
  - libgomp
  - libiconv
  - libpng
  - libtiff
  - libwebp
  - libwebp-base
  - lz4-c
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - m2-ncurses
  - m2-nettle
  - numpy-base
  - openh264
  - openssl
  - pip
  - python_abi
  - pytorch
  - pytorch-mutex
  - m2-libreadline
  - setuptools
  - sqlite
  - tk
  - typing_extensions
  - tzdata
  - xz
  - zlib
  - zstd
  - pip:
    - certifi
    - charset-normalizer
    - contourpy
    - cvxpy
    - cycler
    - ecos
    - filelock
    - fonttools
    - ftfy
    - huggingface-hub
    - idna
    - kiwisolver
    - matplotlib
    - numpy
    - open-clip-torch
    - osqp
    - packaging
    - pandas
    - patsy
    - pillow
    - plotly
    - pycparser
    - pyopenssl
    - pyparsing
    - pysocks
    - python-dateutil
    - pytz
    - pyyaml
    - qdldl
    - regex
    - requests
    - scipy
    - scs
    - seaborn
    - six
    - statsmodels
    - tenacity
    - torch
    - torchaudio
    - torchvision
    - tqdm
    - typing-extensions
    - urllib3
    - wcwidth
    - wheel
